### ISSUE TITLE
HOI for real scenario deployment

### ISSUE THREAD

**Issue by dragen1860** [kakaobrain/HOTR#6]
Dear author:
  I tested some influential HOI algorithms, such as iCAN, and found these algorithms may perform good in public dataset. However, when transfered to real scenario images, such as the photos taken by my mobile phone, i found the performance dropped severely. My team are trying to make HOI work on some real scenario, therefore I would invite you to reccomend a neat and effective algorithm to use. Which algorithm will you reccommend,?  Thank you.

**Comment by meliketoy** [comment]
@dragen1860 As far as I know the gap between the performance of HOI detection benchmark settings and real-world datasets leaves quite a gap since I) the objects in HOI detection benchmark sets are not exhaustively annotated and ii) exhaustive labeling in relationships is extremely expensive.

Papers such as PPDM show new datasets that are more close to real-world applications and ST-HOI that shows results in video datasets, which would might be helpful for your situation :) You might like to take a look in to these algorithms.
